### ISSUE TITLE
Always Launching Safari Instead of Chrome

### ISSUE THREAD

**Issue by c0rb3aux** [dionmunk/popclip-grammarly#1]
Upon installing the Popclip extension I received a macOS prompt to choose where is my 'Chrome' browser located. Thinking that this is the new prompt I chose Safari. Now, when I want to switch back to Chrome, even when I select Chrome from the drop-down menu in Popclip the app defaults to Safari. 

I looked around, also dug into the .plist files, but couldn't find a place where I could overwrite/change the initial (bad) choice. 

Any ideas about how to revert to the default, as intended, behavior?

Thanks!

-Tom  
![Xnip2020-07-27_2-24-50 PM](https://user-images.githubusercontent.com/50241556/88541407-fbc2ea80-d014-11ea-8393-2496b87987e6.png)

**Comment by dionmunk** [comment]
Try reinstalling the plugin. It should prompt you for the web browser again.

**Comment by c0rb3aux** [comment]
> Try reinstalling the plugin. It should prompt you for the web browser again.

Tried several times, but unfortunately, it doesn't follow the selected option, nor do I get the prompt again. The dialog I got the first time was macOS system level, which makes me suspect the issue needs to be fixed there -- app calls on Chrome but chooses Safari due to the selection made upon first launch.

What do you think?     
![Grammarly Popclip Issue](https://user-images.githubusercontent.com/50241556/88628139-c0c0c580-d0ad-11ea-97cf-b2591a6a3f31.gif)

**Comment by dionmunk** [comment]
@c0rb3aux Got it. What you have to do is download the plugin, double click the `Grammarly.popclipext` file and Grammarly will ask you if you want to install the plugin. Choose "Install Grammarly," and at that point, you should get prompted again for the browser you wish to use, and it should remember what you choose.

Let me know if that does the trick. I remember having issues with this myself when I was building the plugin.

**Comment by c0rb3aux** [comment]
Thanks for being patient with me @dionmunk. I really appreciate the troubleshooting. 

Tried your suggestion, but no luck. Same result as before. It seems this issue has returned to haunt you, haha. 

I'm no coding expert such as yourself, far from it, but something tells me it's macOS calling on the incorrect browser. 

I also tried deleting and then installing the prior version of your Grammarly extension, but the behavior would remain unchanged. I even went as far as fully deleting PopClip and then installing and loading all the extensions to see if that works. The status quo remained. 😔

**Comment by dionmunk** [comment]
What version of macOS are you running?

**Comment by c0rb3aux** [comment]
10.15.6

**Comment by dionmunk** [comment]
I can't, for the life of me, reproduce the problem. I'm going to see if I can get a few of my colleagues to test it out to see if the same thing will happen to them.

**Comment by c0rb3aux** [comment]
I really appreciate that you're trying. I began to concede, but I'll be trying out macOS Big Sur (fresh install) and see whether I can replicate the dialog. I guess a screen recording will not help much, or? Is there anything I can do to pass on the data for analysis? 
Has anybody else come across this issue?

Thanks again for trying.

**Comment by c0rb3aux** [comment]
### **SOLVED**: Got It Working by Tinkering in AppleScript
What I essentially tried to do, in a desperate attempt to get the extension to work, is to bypass the AppleScript that calls on Safari and make it default to Chrome/Brave under all circumstances. For some odd reason, I made a blundering typo with "Brawe," which prompted the AppleScript to ask me about the browser. 

I guess you could say I "typoed" into it. That solved the issue for me. 
Afterward, I corrected the typo, re-installed the extension and it continued to work as advertised. 

![Where is Brave Browser](https://user-images.githubusercontent.com/50241556/90483436-fe58c180-e134-11ea-96b2-e16541a0b170.png)

**Comment by dionmunk** [comment]
Nice! Very interesting that that little change would do the trick. I wonder if Popclip is caching something somewhere. I'll do some more tweaking and see if I can't get it to cooperate. Thanks for continuing to try things!
